### ISSUE TITLE
dependency installation

### ISSUE THREAD

**Issue by GrostRane** [Uniswap/interface#5962]
when installing dependencies with the yarn install command, this happens. where can i find this file?

![image](https://user-images.githubusercontent.com/79666398/218231130-1d27ef44-8052-4417-8797-b8343cb17ef8.png)

```
Generate outputs
  ❯ Generate to src/graphql/data/__generated__/types-and-hooks.ts
    ✖
            Failed to load schema from ./src/graphql/data/schema.graphql:


          Unable to find any GraphQL type definitions for the following pointers:

              - ./src/graphql/data/schema.graphql

            Error:
          Unable to find any GraphQL type definitions for the following po…
    ◼ Load GraphQL documents
    ◼ Generate
```

**Comment by cong1223** [comment]
+1，anyone can help me?

**Comment by easoninus** [comment]
It seems that node fetch schema from https://api.uniswap.org was failed because of network unreachable.
I fixed it by enable http proxy. In my case, I'm using proxy client Clashx Pro on mac and enable ’增强模式‘ to make sure node command pass through the proxy.
And you can also use other tools to make the node command pass through the proxy

**Comment by surrenderoz** [comment]
How you solve this problem I have same problem and I'm not using any proxy.

**Comment by MarcusWentz** [comment]
Having the same issue. 

I have
```
node -v
```
return
```
v18.16.0
```
and
```
yarn -v
```
return
```
1.22.19
```

**Comment by surrenderoz** [comment]
@easoninus Can you help here?

**Comment by MarcusWentz** [comment]
I followed this guide to reset my proxy settings:
https://bobbyhadz.com/blog/there-appears-to-be-trouble-with-your-network-connection-yarn

However, I am still getting the same error I mentioned here:
https://github.com/Uniswap/interface/issues/5962#issuecomment-1735852614

@easoninus 

How did you setup your proxy exactly with yarn? 
Do you have a guide that you followed to set this up?

**Comment by plondon** [comment]
Hi, we've recently updated this package to make [local development](https://github.com/Uniswap/interface?tab=readme-ov-file#install--apps) easier as well as updated our [contribution guide](https://github.com/Uniswap/interface/blob/main/CONTRIBUTING.md).

Note that you will need to add the __generated__ folder for now after git cloning the repo: https://github.com/Uniswap/interface/discussions/7718
